version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app:cached

  db:
    image: mysql:8
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    # No se expone a menos que sea necesario:
    # ports:
    #   - "3307:3306"
    networks:
      - default

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  mysqld_exporter:
    image: prom/mysqld-exporter
    volumes:
      - ./monitoreo/mysql-exporter.cnf:/etc/.my.cnf
    command:
      - "--config.my-cnf=/etc/.my.cnf"
    depends_on:
      - db
    ports:
      - "9104:9104"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  db_data:
  frontend_node_modules:
  grafana_data:
